require("plugin.nvim-lspconfig")
require("plugin.completion-nvim")
require("plugin.neosnippet")
require("plugin.undotree")
-- require("plugin.lexima")
require("plugin.lightline")
require("plugin.nvim-colorizer")
require("plugin.nvim-treesitter")
require('plugin.ale')
require('plugin.telescope')
